// Generated by CoffeeScript 1.7.1
(function() {
  var Particle, grasky;

  grasky = window.grasky != null ? window.grasky : window.grasky = {};

  grasky.ForceDirectedLayout = (function() {
    var BOUNDRY_DISTANCE, DRAG_CONSTANT, NUM_ITERATIONS, REPULSION_CONSTANT, SPRING_CONSTANT;

    function ForceDirectedLayout() {}

    SPRING_CONSTANT = 0.001;

    REPULSION_CONSTANT = 0.02;

    DRAG_CONSTANT = 0.05;

    NUM_ITERATIONS = 2000;

    BOUNDRY_DISTANCE = 20;

    ForceDirectedLayout.prototype.getLayout = function(nodeCount, edges) {
      var attractiveForce, edge, i, iteration, other, particle, particle1, particle2, particles, _i, _j, _k, _l, _len, _len1, _len2, _len3, _m, _results;
      particles = (function() {
        var _i, _results;
        _results = [];
        for (i = _i = 0; 0 <= nodeCount ? _i < nodeCount : _i > nodeCount; i = 0 <= nodeCount ? ++_i : --_i) {
          _results.push(new Particle);
        }
        return _results;
      })();
      for (iteration = _i = 0; 0 <= NUM_ITERATIONS ? _i < NUM_ITERATIONS : _i > NUM_ITERATIONS; iteration = 0 <= NUM_ITERATIONS ? ++_i : --_i) {
        for (_j = 0, _len = particles.length; _j < _len; _j++) {
          particle = particles[_j];
          particle.position.add(particle.velocity);
          particle.velocity.add(this._dragForce(particle));
          particle.velocity.add(this._boundryRepulsiveForce(particle));
          for (_k = 0, _len1 = particles.length; _k < _len1; _k++) {
            other = particles[_k];
            if (particle !== other) {
              particle.velocity.add(this._repulsiveForce(particle, other));
            }
          }
        }
        for (_l = 0, _len2 = edges.length; _l < _len2; _l++) {
          edge = edges[_l];
          particle1 = particles[edge[0]];
          particle2 = particles[edge[1]];
          attractiveForce = this._edgeAttractiveForce(particle1, particle2);
          particle1.velocity.add(attractiveForce);
          particle2.velocity.sub(attractiveForce);
        }
      }
      _results = [];
      for (_m = 0, _len3 = particles.length; _m < _len3; _m++) {
        particle = particles[_m];
        _results.push(particle.position);
      }
      return _results;
    };

    ForceDirectedLayout.prototype._dragForce = function(particle) {
      return particle.velocity.clone().multiplyScalar(-DRAG_CONSTANT);
    };

    ForceDirectedLayout.prototype._repulsiveForce = function(particle, other) {
      var direction, distance;
      distance = particle.position.distanceTo(other.position);
      direction = new THREE.Vector3().subVectors(particle.position, other.position);
      return direction.setLength(REPULSION_CONSTANT / distance);
    };

    ForceDirectedLayout.prototype._edgeAttractiveForce = function(particle, other) {
      var direction, distance;
      distance = particle.position.distanceTo(other.position);
      direction = new THREE.Vector3().subVectors(other.position, particle.position);
      return direction.setLength(SPRING_CONSTANT * distance);
    };

    ForceDirectedLayout.prototype._boundryRepulsiveForce = function(particle) {
      var distance;
      distance = Math.max(BOUNDRY_DISTANCE - particle.position.length(), 1);
      return particle.position.clone().setLength(-REPULSION_CONSTANT / distance);
    };

    return ForceDirectedLayout;

  })();

  Particle = (function() {
    function Particle() {
      this.position = new THREE.Vector3(Math.random(), Math.random(), Math.random());
      this.velocity = new THREE.Vector3;
    }

    return Particle;

  })();

}).call(this);
