// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    var canvas, fixCanvas, graph;
    canvas = $('#grasky-canvas')[0];
    graph = new grasky.Graph(canvas);
    new grasky.GraphGenerator().gilbertGraph(graph, 25, 0.08);
    graph.applyLayout(new grasky.ForceDirectedLayout);
    fixCanvas = function() {
      canvas.style.width = window.innerWidth + 'px';
      canvas.style.height = (window.innerHeight - $('#controls').height()) + 'px';
      return graph.fixViewBounds();
    };
    fixCanvas();
    $(window).resize(fixCanvas);
    $('#grasky-canvas').mousedown(function(e) {
      return e.preventDefault();
    });
    $('#lattice-layout-item').click(function() {
      return graph.applyLayout(new grasky.LatticeLayout);
    });
    $('#sphere-layout-item').click(function() {
      return graph.applyLayout(new grasky.SphereLayout);
    });
    return $('#auto-layout-item').click(function() {
      return graph.applyLayout(new grasky.ForceDirectedLayout);
    });
  });

}).call(this);
